In [2]:
import numpy as np

In [5]:
# arange - excludes last index

# np.arange(start,stop,step)
arr = np.arange(0,10,2) # 0 - start index, 10 - stop index, 2 - gap of 2 in given range
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.arange(0,100,2) 
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [12]:
arr = np.arange(0,100,50) 
arr

array([ 0, 50])

In [7]:
# linspace - include last index

# np.linspace(start,stop,num)
arr = np.linspace(0,10,5) # 0 - start at no. zero, 10 - stop at no. 10, 5 - divide equally the given range in equal parts(num of elements)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
arr = np.linspace(0,100,5) 
arr

array([  0.,  25.,  50.,  75., 100.])

In [9]:
arr = np.linspace(0,100,2) 
arr

array([  0., 100.])

In [10]:
arr = np.linspace(0,100,3) 
arr

array([  0.,  50., 100.])

#### Basic Usage

In [2]:
import numpy as np
a = np.arange(0,10,2)
b = np.linspace(0,10,5)
print("arange (0,10,2):",a)
print("linspace (0,10,5):",b)

arange (0,10,2): [0 2 4 6 8]
linspace (0,10,5): [ 0.   2.5  5.   7.5 10. ]


#### Float Behavior

In [3]:
print("\narange with float step (miss endpoint):")
print(np.arange(0,1,0.2))
print("\nlinspace with exact number of points :")
print(np.linspace(0,10,6))


arange with float step (may miss endpoint):
[0.  0.2 0.4 0.6 0.8]

linspace with eaxct number of points :
[ 0.  2.  4.  6.  8. 10.]


#### Endpoint Control

In [4]:
print("\nlinspace without endpoint:") 
print(np.linspace(0,10,5,endpoint=False)) # To exclude end value


linspace without endpoint:
[0. 2. 4. 6. 8.]


#### Length Comparison

In [5]:
print("\nNumber of elements :")
print("len(arange) :",len(np.arange(0,10,2)))
print("len(linspace) :",len(np.linspace(0,10,5)))


Number of elements :
len(arange) : 5
len(linspace) : 5


#### Precision Demonstration

In [6]:
print("\nPrecision check :")
arr = np.arange(0,1,0.1)
lin = np.linspace(0,1,10)
print("arange:", arr)
print("linspace:",lin)


Precision check :
arange: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
linspace: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
