In [1]:
import numpy as np

In [23]:
#step1:create array
arr=np.arange(55,65)
print("Original Array :\n",arr)

Original Array :
 [55 56 57 58 59 60 61 62 63 64]


In [24]:
#step2:Apply condition(vectorized)
mask=arr>58
print("\nCondition (arr>58):",mask)


Condition (arr>58): [False False False False  True  True  True  True  True  True]


In [10]:
#step3:Apply Boolean mask
boolean_arrr=arr>58
boolean_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
#step4:Filter values
filtered=arr[mask]
print("\filtered values:",filtered)

iltered values: [59 60 61 62 63 64]


In [27]:
#direct filtering
print("Direct filtering (best practice):",arr[arr>58])

Direct filtering (best practice): [59 60 61 62 63 64]


In [29]:
#multiple conditions
print("\nValues between 57 and 62:",arr[(arr>57)&(arr<63)])


Values between 57 and 62: [58 59 60 61 62]


#### Example: Student Marks

In [18]:
import numpy as np
marks = np.array([67,32,89,56,34,36])
marks

array([67, 32, 89, 56, 34, 36])

In [30]:
passing_students_boolean = marks>35
print(passing_students_boolean)

[ True False  True  True False  True]


In [31]:
print(marks[passing_students_boolean])

[67 89 56 36]


#### Shallow Copy and Deep Copy

In [32]:
a = np.array([10,20,30,40,50,60])

In [33]:
# Shallow Copy(View)
b = a[0:5]
print("Original a :",a)
print("Shallow Copy b :",b)

Original a : [10 20 30 40 50 60]
Shallow Copy b : [10 20 30 40 50]


In [34]:
b[0]=999
print("\nAfter modifying b :")
print("a:",a)
print("b:",b)


After modifying b :
a: [999  20  30  40  50  60]
b: [999  20  30  40  50]


In [35]:
# Deep Copy
c=a.copy()

In [36]:
c[1]=888
print("\nAfter modifying c:")
print("a:",a)
print("c:",c)


After modifying c:
a: [999  20  30  40  50  60]
c: [999 888  30  40  50  60]
