In [1]:
import numpy as np

In [4]:
# Create
arr = np.array([1,2,3,4])
lst=[1,2,3,4]
arr

array([1, 2, 3, 4])

In [5]:
# Add 
print(arr+5)
print([x+5 for x in lst])

[6 7 8 9]
[6, 7, 8, 9]


In [13]:
# (Time) - Add 5 and measure time for numpy
import time
start_time = time.time()
print(arr+5)
end_time = time.time()
execution_time = end_time - start_time
print(f"\nExecution Time : {execution_time} seconds")
print([x+5 for x in lst])

[6 7 8 9]

Execution Time : 0.0007994174957275391 seconds
[6, 7, 8, 9]


In [23]:
# (Time) - Add 5 and measure time for list
start_time = time.time()
print([x+5 for x in lst])
end_time = time.time()
execution_time = end_time - start_time
print(f"\nExecution Time : {execution_time} seconds")

[6, 7, 8, 9]

Execution Time : 0.0003552436828613281 seconds


In [9]:
# Multiply
print(arr*5)
print([x*5 for x in lst])

[ 5 10 15 20]
[5, 10, 15, 20]


In [10]:
# Square
print(arr**2)
print([x**2 for x in lst])

[ 1  4  9 16]
[1, 4, 9, 16]


In [14]:
# Mean
print(np.mean(arr))
print(sum(lst)/len(lst))

2.5
2.5


In [15]:
# Even Filter
print(arr[arr%2 == 0])
print([x for x in lst if x % 2 == 0])

[2 4]
[2, 4]


In [16]:
# 2D Data
print(np.array([[1,2],[3,4]]))
print([[1,2],[3,4]])

[[1 2]
 [3 4]]
[[1, 2], [3, 4]]


In [17]:
# Add Two - NumPy
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [21]:
# Add Two - List 
a = [1,2,3]
b = [4,5,6]
print([x+y for x, y in zip(a,b)])

# zip(a,b) -- read the same element of array and array b at the same time, when processing a[0], also process b[0]
# for x,y in zip(a,b) -- a[0] - x and b[0] - y
# x+y for x,y in zip(a,b) - Add a and y, which means a[0] and b[0], next time a[1] and b[1], becoz we have a "for" loop

[5, 7, 9]


In [22]:
# Broadcasting - NumPy
print(arr+1)

# Broadcasting - List
# Not possible

[2 3 4 5]


In [25]:
# Conditional Replace
arr[arr>2] = 0
print(arr)

lst=[1,2,3,4]
print([0 if x>2 else x for x in lst])

[1 2 0 0]
[1, 2, 0, 0]
